### ISSUE TITLE
Still shows bot tag when click

### ISSUE THREAD

**Issue by carterlasalle** [BenSegal855/webhook-tag#2]
Title says it all :)

![image](https://user-images.githubusercontent.com/50027436/106933718-16fe6900-66ce-11eb-9d35-3a6dc8d3f926.png)

**Comment by BenSegal855** [comment]
Added in [9b7f134](https://github.com/BenSegal855/webhook-tag/commit/9b7f1344d8e88b96fab088eab6ea9daaa02bf582)
