### ISSUE TITLE
r.isClaimed() is not a function [TypeError Discord  Powercord Crashing]

### ISSUE THREAD

**Issue by aoqia194** [BenSegal855/webhook-tag#6]
`[2021-05-20 00:50:34] [WINDOW] [ERROR] Error: Uncaught TypeError: r.isClaimed is not a function`
That is the last line that is wrote in the log before it crashes. Removing the plugin from the Plugins folder in powercord does fix this problem. Although I did a search through files and it doesn't seem like "r.isClaimed()" is a function. (Or so I thought, not sure if it is or not). Don't know if an update caused this but I hopped on and it started infinite loading. I looked at many logs and got the same line before it crashes.
Now you know why powercord is crashing :)

**Comment by BenSegal855** [comment]
I cannot reproduce this. Can you please provide a screenshot of the full error logged to the console.

**Comment by codexecYT** [comment]
Sorry for late response. I am getting the video right now.

**Comment by aoqia194** [comment]
So as I was trying to replicate the problem, it wasn't happening as how I was experiencing it before. I think I may have encountered a buggy webhook bot in a Discord server or something. I can't get this to replicate. I will close this until further information.

If anyone experiences this issue, just RE- git clone this repository and it will work fine.
Maybe something to do with cache or some corrupted information, or even Powercord updates clashing with the code of this project.
